name: 'Build Website'

on:
  pull_request:
    branches:    
      - 'website/**'
      - 'website_**'
  push:
    branches:    
      - 'website/**'
      - 'website_**'

jobs:
  build_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Building the Website
        run: nix-shell --run "make build"