name: 'Build Website'

on:
  pull_request:
    branches:
      - 'website/**'
      - 'website_**'
  push:
    branches:
      - 'website/**'
      - 'website_**'

jobs:
  build_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build the website to public directory
        uses: gaol/hugo-gh-action@v1.2
