name: 'Build Website'

on:
  pull_request:
    branches:
      - 'website/**'
      - 'website_**'
  push:
    branches:
      - 'website/**'
      - 'website_**'

jobs:
  build_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build
        run: devenv shell build
