name: 'Build Website'

on:
  pull_request:
    branches:
      - 'website/**'
      - 'website_**'
  push:
    branches:
      - 'website/**'
      - 'website_**'

jobs:
  build_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true

      - name: Setup Asciidoc
        run: sudo apt install asciidoctor

      - name: Build
        run: hugo --minify
