name: 'Release Curriculum vitæ'

on:
  push:
    tags:
      - 'cv/**'
      - 'cv_**'

jobs:
  release_curriculum_vitae:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0

    # - uses: cachix/install-nix-action@v16
    #   with:
    #     nix_path: nixpkgs=channel:nixos-unstable

    # - name: Building the CV
    #   run: nix-shell --run "make"

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: NicolasGuilloux_CV.tex
        latexmk_use_lualatex: true

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          NicolasGuilloux_CV.pdf