name: 'Release Curriculum vitæ'

on:
  push:
    tags:
      - 'cv/**'
      - 'cv_**'

jobs:
  release_curriculum_vitae:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: NicolasGuilloux_CV.tex
        latexmk_use_lualatex: true
        extra_fonts: './fonts/*'

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          NicolasGuilloux_CV.pdf